strike_buckets:
  - lower: 0.0
    upper: 25.0

  - lower: 25.0
    upper: 35.0

  - lower: 35.0
    upper: 45.0

  - lower: 45.0
    upper: 55.0

  - lower: 55.0
    upper: 65.0

  - lower: 65.0
    upper: 75.0

  - lower: 75.0
    upper: 85.0

  - lower: 85.0
    upper: 95.0

  - lower: 95.0
    upper: 105.0

  - lower: 105.0
    upper: 115.0

  - lower: 115.0
    upper: 125.0

  - lower: 125.0
    upper: 135.0

  - lower: 135.0
    upper: 145.0

  - lower: 145.0
    upper: 155.0

  - lower: 155.0
    upper: 165.0

  - lower: 165.0
    upper: 175.0

  - lower: 175.0
    upper: 9999.0
